### ISSUE TITLE
Failed on my blog site

### ISSUE THREAD

**Issue by SYuan03** [antfu/markdown-it-github-alerts#5]
![image](https://github.com/antfu/markdown-it-github-alerts/assets/91423966/857fbc21-862c-4038-bb2e-c3048b4b93dc)
Is it a problem of my hexo theme?
I use it like this in my _config.yml
![image](https://github.com/antfu/markdown-it-github-alerts/assets/91423966/64d9c409-8030-4fff-ab3c-b8c94227a7c4)
Could you please have a look?Orz

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by zhdbk3** [comment]
> We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

I'm also experiencing this issue.

Here's a minimal reproduction:

(I'm using `pnpm`, but other package managers should yield similar results)

# Initialize blog

Execute the following commands in an appropriate directory:

```shell
pnpm create hexo minimal-reproduction
cd minimal-reproduction
pnpm approve-builds
```

# Configure blog

## Replace built-in marked with markdown-it

Execute:

```shell
pnpm uninstall hexo-renderer-marked
pnpm install hexo-renderer-markdown-it
```

At this point, executing `hexo server` to preview the blog should work normally.

## Install and configure markdown-it-github-alerts

Execute:

```shell
pnpm install markdown-it-github-alerts
```

Add the following content to the end of the project's `_config.yml`:

```yaml
markdown:
  plugins:
    - markdown-it-github-alerts
```

Then execute:

```shell
hexo server
```

Got an error:

```text
ERROR Plugin load failed: hexo-renderer-markdown-it
TypeError: plugin.apply is not a function
    at MarkdownIt.use (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\markdown-it@13.0.2\node_modules\markdown-it\lib\index.js:497:10)
    at D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\hexo-renderer-markdown-it@7.1.1\node_modules\hexo-renderer-markdown-it\lib\renderer.js:55:23
    at Array.reduce (<anonymous>)
    at new Renderer (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\hexo-renderer-markdown-it@7.1.1\node_modules\hexo-renderer-markdown-it\lib\renderer.js:39:29)
    at D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\hexo-renderer-markdown-it@7.1.1\node_modules\hexo-renderer-markdown-it\index.js:32:18
    at D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\hexo@7.3.0_chokidar@3.6.0\node_modules\hexo\dist\hexo\index.js:255:20
    at tryCatcher (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (D:\WebstormProjects\minimal-reproduction\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:485:21)
```

The plugin wasn't loaded correctly.

Hope you can reopen the issue and fix it! Thank you very much! @antfu

**Comment by fjqz177** [comment]
# Hexo + NexT：完整实现 GitHub 风格 Alerts（一比一还原）

## 问题

在 `_config.yml` 的 `markdown.plugins` 中启用 `markdown-it-github-alerts` 后，Hexo 构建报错无法加载此插件。即使解决了加载问题，渲染出的 HTML 也没有任何样式。

## 根因

两层不兼容 + 缺少样式：

1. **ESM vs CJS**：`markdown-it-github-alerts` 是纯 ESM 包（`"type": "module"`，入口 `./dist/index.mjs`），而 `hexo-renderer-markdown-it` 用 `require()` 加载插件——Node.js 的 `require()` 无法加载 ESM 模块。
2. **Hexo vm 沙箱限制**：Hexo 用 `vm.runInThisContext()` 执行 `scripts/` 下的脚本，该上下文不支持 `import()`，所以动态导入也行不通。
3. **无 CSS**：插件只生成 HTML 结构，CSS 样式需要使用者自行引入，Hexo 不会自动加载 `node_modules` 里的 CSS 文件。

## 完整解决方案

需要修改/创建 **3 个文件**，下面逐一给出完整代码。

---

### 第一步：保持 `_config.yml` 中插件为注释状态

在 `_config.yml` 的 markdown plugins 列表中，确保 `markdown-it-github-alerts` 这一行是注释掉的（**不要启用它**，否则会触发 `require()` 加载 ESM 的报错）：

```yaml
# 位于 _config.yml 的 markdown.plugins 部分（大约第 189 行）
plugins:
  - markdown-it-deflist
  - markdown-it-emoji
  - markdown-it-footnote
  - markdown-it-ins
  - markdown-it-mark
  - markdown-it-sub
  - markdown-it-sup
  - markdown-it-align
  - markdown-it-task-lists
  # - markdown-it-github-alerts    ← 保持注释！
```

---

### 第二步：创建 `scripts/markdown-it-github-alerts.js`

在项目根目录的 `scripts/` 文件夹下创建此文件。它将插件的核心逻辑（来自 `node_modules/markdown-it-github-alerts/dist/index.mjs` v1.0.1）从 ESM 改写为 CJS，并通过 Hexo 的 `markdown-it:renderer` filter 注册到 markdown-it。

**完整代码：**

```js
'use strict';

// markdown-it-github-alerts 是纯 ESM 包，无法被 hexo-renderer-markdown-it 的
// require() 加载，也无法在 Hexo scripts/ 的 vm 上下文中用 import() 加载。
// 这里直接内联插件逻辑以绕过模块兼容性问题。
// 源码来自: node_modules/markdown-it-github-alerts/dist/index.mjs (v1.0.1)

const DEFAULT_GITHUB_ICONS = {
  note: '<svg class="octicon octicon-info mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8Zm8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13ZM6.5 7.75A.75.75 0 0 1 7.25 7h1a.75.75 0 0 1 .75.75v2.75h.25a.75.75 0 0 1 0 1.5h-2a.75.75 0 0 1 0-1.5h.25v-2h-.25a.75.75 0 0 1-.75-.75ZM8 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>',
  tip: '<svg class="octicon octicon-light-bulb mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M8 1.5c-2.363 0-4 1.69-4 3.75 0 .984.424 1.625.984 2.304l.214.253c.223.264.47.556.673.848.284.411.537.896.621 1.49a.75.75 0 0 1-1.484.211c-.04-.282-.163-.547-.37-.847a8.456 8.456 0 0 0-.542-.68c-.084-.1-.173-.205-.268-.32C3.201 7.75 2.5 6.766 2.5 5.25 2.5 2.31 4.863 0 8 0s5.5 2.31 5.5 5.25c0 1.516-.701 2.5-1.328 3.259-.095.115-.184.22-.268.319-.207.245-.383.453-.541.681-.208.3-.33.565-.37.847a.751.751 0 0 1-1.485-.212c.084-.593.337-1.078.621-1.489.203-.292.45-.584.673-.848.075-.088.147-.173.213-.253.561-.679.985-1.32.985-2.304 0-2.06-1.637-3.75-4-3.75ZM5.75 12h4.5a.75.75 0 0 1 0 1.5h-4.5a.75.75 0 0 1 0-1.5ZM6 15.25a.75.75 0 0 1 .75-.75h2.5a.75.75 0 0 1 0 1.5h-2.5a.75.75 0 0 1-.75-.75Z"></path></svg>',
  important: '<svg class="octicon octicon-report mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M0 1.75C0 .784.784 0 1.75 0h12.5C15.216 0 16 .784 16 1.75v9.5A1.75 1.75 0 0 1 14.25 13H8.06l-2.573 2.573A1.458 1.458 0 0 1 3 14.543V13H1.75A1.75 1.75 0 0 1 0 11.25Zm1.75-.25a.25.25 0 0 0-.25.25v9.5c0 .138.112.25.25.25h2a.75.75 0 0 1 .75.75v2.19l2.72-2.72a.749.749 0 0 1 .53-.22h6.5a.25.25 0 0 0 .25-.25v-9.5a.25.25 0 0 0-.25-.25Zm7 2.25v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"></path></svg>',
  warning: '<svg class="octicon octicon-alert mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M6.457 1.047c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0 1 14.082 15H1.918a1.75 1.75 0 0 1-1.543-2.575Zm1.763.707a.25.25 0 0 0-.44 0L1.698 13.132a.25.25 0 0 0 .22.368h12.164a.25.25 0 0 0 .22-.368Zm.53 3.996v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 11a1 1 0 1 1-2 0 1 1 0 1 1 2 0Z"></path></svg>',
  caution: '<svg class="octicon octicon-stop mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path d="M4.47.22A.749.749 0 0 1 5 0h6c.199 0 .389.079.53.22l4.25 4.25c.141.14.22.331.22.53v6a.749.749 0 0 1-.22.53l-4.25 4.25A.749.749 0 0 1 11 16H5a.749.749 0 0 1-.53-.22L.22 11.53A.749.749 0 0 1 0 11V5c0-.199.079-.389.22-.53Zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5ZM8 4a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"></path></svg>'
};

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function markdownItGitHubAlerts(md, options) {
  options = options || {};
  const markers = options.markers || ['TIP', 'NOTE', 'IMPORTANT', 'WARNING', 'CAUTION'];
  const icons = options.icons || DEFAULT_GITHUB_ICONS;
  const matchCaseSensitive = options.matchCaseSensitive || false;
  const titles = options.titles || {};
  const classPrefix = options.classPrefix || 'markdown-alert';

  const markerNameRE = markers === '*' ? '\\w+' : markers.join('|');
  const RE = new RegExp(
    '^\\\\?\\[\\!(' + markerNameRE + ')\\]([^\\n\\r]*)',
    matchCaseSensitive ? '' : 'i'
  );

  md.core.ruler.after('block', 'github-alerts', function (state) {
    var tokens = state.tokens;
    for (var i = 0; i < tokens.length; i++) {
      if (tokens[i].type === 'blockquote_open') {
        var open = tokens[i];
        var startIndex = i;
        while (tokens[i] && tokens[i].type !== 'blockquote_close' && i <= tokens.length)
          i += 1;
        var close = tokens[i];
        var endIndex = i;
        var firstContent = tokens.slice(startIndex, endIndex + 1).find(function (token) {
          return token.type === 'inline';
        });
        if (!firstContent) continue;
        var match = firstContent.content.match(RE);
        if (!match) continue;
        var type = match[1].toLowerCase();
        var title = match[2].trim() || (titles[type] != null ? titles[type] : capitalize(type));
        var icon = icons[type] != null ? icons[type] : '';
        firstContent.content = firstContent.content.slice(match[0].length).trimStart();
        open.type = 'alert_open';
        open.tag = 'div';
        open.meta = { title: title, type: type, icon: icon };
        close.type = 'alert_close';
        close.tag = 'div';
      }
    }
  });

  md.renderer.rules.alert_open = function (tokens, idx) {
    var meta = tokens[idx].meta;
    return '<div class="' + classPrefix + ' ' + classPrefix + '-' + meta.type + '"><p class="' + classPrefix + '-title">' + meta.icon + meta.title + '</p>';
  };
}

hexo.extend.filter.register('markdown-it:renderer', function (md) {
  md.use(markdownItGitHubAlerts);
});
```

---

### 第三步：在 `source/_data/styles.styl` 中添加 GitHub Alerts 样式

NexT 主题通过 `_config.next.yml` 中的 `custom_file_path.style` 配置加载自定义样式。确认 `_config.next.yml` 中有以下配置（默认已启用）：

```yaml
# _config.next.yml 第 32 行
custom_file_path:
  style: source/_data/styles.styl
```

然后在 `source/_data/styles.styl` **末尾**追加以下完整的 CSS 代码（Stylus 是 CSS 的超集，直接写 CSS 语法即可）：

```css
// ============================================================
// GitHub-style Alerts (markdown-it-github-alerts)
// 1:1 reproduction of GitHub's native alert rendering
// ============================================================

// --- Color variables (light mode) ---
:root {
  --color-note: #0969da;
  --color-tip: #1a7f37;
  --color-warning: #9a6700;
  --color-severe: #bc4c00;
  --color-caution: #d1242f;
  --color-important: #8250df;
}

// --- Color variables (dark mode via media query) ---
@media (prefers-color-scheme: dark) {
  :root {
    --color-note: #2f81f7;
    --color-tip: #3fb950;
    --color-warning: #d29922;
    --color-severe: #db6d28;
    --color-caution: #f85149;
    --color-important: #a371f7;
  }
}

// --- Base layout ---
.markdown-alert {
  padding: 0.5rem 1rem;
  margin-bottom: 16px;
  color: inherit;
  border-left: .25em solid #888;
}

.markdown-alert > :first-child {
  margin-top: 0;
}

.markdown-alert > :last-child {
  margin-bottom: 0;
}

.markdown-alert .markdown-alert-title {
  display: flex;
  font-weight: 500;
  align-items: center;
  line-height: 1;
}

.markdown-alert .markdown-alert-title .octicon {
  margin-right: 0.5rem;
  display: inline-block;
  overflow: visible !important;
  vertical-align: text-bottom;
  fill: currentColor;
}

// --- Per-type colors ---
.markdown-alert.markdown-alert-note {
  border-left-color: var(--color-note);
}
.markdown-alert.markdown-alert-note .markdown-alert-title {
  color: var(--color-note);
}

.markdown-alert.markdown-alert-tip {
  border-left-color: var(--color-tip);
}
.markdown-alert.markdown-alert-tip .markdown-alert-title {
  color: var(--color-tip);
}

.markdown-alert.markdown-alert-important {
  border-left-color: var(--color-important);
}
.markdown-alert.markdown-alert-important .markdown-alert-title {
  color: var(--color-important);
}

.markdown-alert.markdown-alert-warning {
  border-left-color: var(--color-warning);
}
.markdown-alert.markdown-alert-warning .markdown-alert-title {
  color: var(--color-warning);
}

.markdown-alert.markdown-alert-caution {
  border-left-color: var(--color-caution);
}
.markdown-alert.markdown-alert-caution .markdown-alert-title {
  color: var(--color-caution);
}
```

---

### 第四步：构建验证

```bash
hexo clean && hexo generate
```

构建成功后，在文章中使用标准的 GitHub Alerts 语法即可：

```markdown
> [!NOTE]
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]
> Crucial information necessary for users to succeed.

> [!WARNING]
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

---

## 渲染效果

每种 Alert 都会渲染为带有彩色左边框 + 对应颜色 SVG 图标 + 标题的卡片：

| 类型 | 图标 | 浅色模式颜色 | 深色模式颜色 |
|------|------|-------------|-------------|
| Note | ℹ️ 信息圆圈 | `#0969da` 蓝色 | `#2f81f7` |
| Tip | 💡 灯泡 | `#1a7f37` 绿色 | `#3fb950` |
| Important | 💬 对话框 | `#8250df` 紫色 | `#a371f7` |
| Warning | ⚠️ 三角感叹号 | `#9a6700` 黄色 | `#d29922` |
| Caution | 🛑 八角停止 | `#d1242f` 红色 | `#f85149` |

生成的 HTML 结构：

```html
<div class="markdown-alert markdown-alert-note">
  <p class="markdown-alert-title">
    <svg class="octicon octicon-info mr-2" viewBox="0 0 16 16" ...>...</svg>
    Note
  </p>
  <p>Highlights information that users should take into account, even when skimming.</p>
</div>
```

---

## 原理总结

| 层 | 问题 | 解决方式 |
|----|------|---------|
| 插件加载 | ESM 包无法被 `require()` 加载 | 内联插件源码到 `scripts/`，转为 CJS |
| Hexo 沙箱 | `vm.runInThisContext()` 不支持 `import()` | 避免动态导入，直接用 CJS 函数 |
| 注册方式 | 不能用 `_config.yml` 的 plugins 配置 | 用 `hexo.extend.filter.register('markdown-it:renderer', ...)` |
| 样式缺失 | 插件不自带样式注入 | 手动将 CSS 加入 NexT 的 `styles.styl` 自定义样式文件 |

此方案同样适用于其他纯 ESM 的 markdown-it 插件。
